
package integration.genhub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 * 
 */
@WebService(name = "GenFileEndpoint", targetNamespace = "http://api/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({ ObjectFactory.class })
public interface GenFileEndpoint {

	/**
	 * 
	 * @param format
	 * @param data
	 * @param templateCode
	 * @return returns integration.genhub.client.GenHubFile
	 */
	@WebMethod
	@WebResult(partName = "genFileRs")
	@Action(input = "http://api/GenFileEndpoint/genFileRequest", output = "http://api/GenFileEndpoint/genFileResponse")
	public GenHubFile genFile(@WebParam(name = "templateCode", partName = "templateCode") String templateCode,
			@WebParam(name = "data", partName = "data") String data,
			@WebParam(name = "format", partName = "format") int format, @WebParam(name = "incFontSize", partName = "incFontSize") Double incFontSize);

	/**
	 * 
	 * @param qrCode
	 * @param fileContent
	 * @return returns integration.genhub.client.GenHubFile
	 */
	@WebMethod
	@WebResult(name = "newQrCodeFile", partName = "newQrCodeFile")
	@Action(input = "http://api/GenFileEndpoint/replaceQrCodeRequest", output = "http://api/GenFileEndpoint/replaceQrCodeResponse")
	public GenHubFile replaceQrCode(@WebParam(name = "fileContent", partName = "fileContent") byte[] fileContent,
			@WebParam(name = "qrCode", partName = "qrCode") String qrCode,
			@WebParam(name = "format", partName = "format") int format,
			@WebParam(name = "protectionType", partName = "protectionType") int protectionType);
}
