
package integration.genhub;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GenFileService", targetNamespace = "http://api/")
public class GenFileService extends Service {
	private final static URL GENFILESERVICE_WSDL_LOCATION;
	private final static WebServiceException GENFILESERVICE_EXCEPTION;
	private final static QName GENFILESERVICE_QNAME = new QName("http://api/", "GenFileService");

	static {
		
		WebServiceException e = null;
		URL url = GenFileService.class.getClassLoader().getResource("");
		try {
			url=new URL(url, "wsdl/GenFileService.wsdl");
			//url = new URL(url,"http://localhost/wsdl/GenFileService.wsdl");
		} catch (MalformedURLException e1) {
			e1.printStackTrace();
		}

		GENFILESERVICE_WSDL_LOCATION = url;
		GENFILESERVICE_EXCEPTION = e;
	}

	public GenFileService() {
		super(__getWsdlLocation(), GENFILESERVICE_QNAME);
	}

	public GenFileService(WebServiceFeature... features) {
		super(__getWsdlLocation(), GENFILESERVICE_QNAME, features);
	}

	public GenFileService(URL wsdlLocation) {
		super(wsdlLocation, GENFILESERVICE_QNAME);
	}

	public GenFileService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, GENFILESERVICE_QNAME, features);
	}

	public GenFileService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public GenFileService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns GenFileEndpoint
	 */
	@WebEndpoint(name = "GenFileEndpointPort")
	public GenFileEndpoint getGenFileEndpointPort() {
		return super.getPort(new QName("http://api/", "GenFileEndpointPort"), GenFileEndpoint.class);
	}

	/**
	 * 
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features
	 *                 not in the <code>features</code> parameter will have their default values.
	 * @return returns GenFileEndpoint
	 */
	@WebEndpoint(name = "GenFileEndpointPort")
	public GenFileEndpoint getGenFileEndpointPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://api/", "GenFileEndpointPort"), GenFileEndpoint.class, features);
	}

	private static URL __getWsdlLocation() {
		if (GENFILESERVICE_EXCEPTION != null) {
			throw GENFILESERVICE_EXCEPTION;
		}
		return GENFILESERVICE_WSDL_LOCATION;
	}

}
