package entity.frwk;

import java.util.Calendar;
import java.util.Date;

// Generated Nov 13, 2019 6:00:05 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * SysParam generated by hbm2java
 */
@Entity
@Table(name = "BSS_PARAM")
public class BssParam implements java.io.Serializable {
	/**
	 * Thoi gian mac dinh cua LSX;
	 */
	public static final String WOTIMAVG = "WOTIMAVG";
	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	private String id;
	@Column(name = "NAME", nullable = false, length = 4000)
	private String name;
	@Column(name = "CODE", unique = true, nullable = false, length = 40)
	private String code;
	@Column(name = "DESCRIPTION", length = 4000)
	private String description;
	@Column(name = "VALUE", length = 4000)
	private String value;
	@JoinColumn(name = "PREVIOUS_VERSION", referencedColumnName = "ID")
	@ManyToOne
	private BssParam previousVersion;
	@Column(name = "CREATED_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	private Date createdDate;

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public BssParam copy() {
		BssParam tmp = new BssParam(this.name, "COPY:" + this.code, this.description, this.value);
		tmp.setCreatedDate(Calendar.getInstance().getTime());
		return tmp;

	}

	public BssParam() {
	}

	public BssParam(String id, String name, String code) {
		this.id = id;
		this.name = name;
		this.code = code;
	}

	public BssParam(String id, String name, String code, String description, String value) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.description = description;
		this.value = value;
	}

	public BssParam(String name, String code, String description, String value) {
		this.name = name;
		this.code = code;
		this.description = description;
		this.value = value;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
