package entity.frwk;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;

// Generated Nov 13, 2019 6:00:05 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * SysParam generated by hbm2java
 */
@Entity
@Table(name = "CAT_CHARGE")
public class CatCharge implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	private String id;
	@Column(name = "NAME", nullable = false, length = 4000)
	private String name;
	@Column(name = "CODE", unique = true, nullable = false, length = 40)
	private String code;
	@Column(name = "DESCRIPTION", length = 4000)
	private String description;
	@JoinColumn(name = "PREVIOUS_VERSION", referencedColumnName = "ID")
	@ManyToOne
	private CatCharge previousVersion;
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "catCharge")
	List<CatChargeDetail> lstCharge = new ArrayList<CatChargeDetail>();
	@Column(name = "CREATED_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	private Date createdDate;

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public CatCharge copy() {
		CatCharge tmp = new CatCharge(this.name, "COPY:" + this.code, this.description);
		tmp.setCreatedDate(Calendar.getInstance().getTime());
		return tmp;

	}

	public CatCharge() {
	}


	public CatCharge(String id, String name, String code, String description) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.description = description;
	}

	public CatCharge(String name, String code, String description) {
		this.name = name;
		this.code = code;
		this.description = description;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public CatCharge getPreviousVersion() {
		return previousVersion;
	}

	public void setPreviousVersion(CatCharge previousVersion) {
		this.previousVersion = previousVersion;
	}

	public List<CatChargeDetail> getLstCharge() {
		return lstCharge;
	}

	public void setLstCharge(List<CatChargeDetail> lstCharge) {
		this.lstCharge = lstCharge;
	}


}
