package entity.frwk;
// Generated Mar 23, 2023 3:45:17 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * SysJob generated by hbm2java
 */
@Entity
@Table(name = "SYS_JOB", uniqueConstraints = @UniqueConstraint(columnNames = "JOB_CLASS"))
public class SysJob implements java.io.Serializable {

	/**
	 * Trang thai stop
	 */
	public static final Byte STS_STOP = 0;
	/**
	 * Trang thai start
	 */
	public static final Byte STS_RUNNING = 1;
	/**
	 * Trang thai disable
	 */
	public static final Byte STS_DISABLED = 2;
	private String id;
	private String jobClass;
	private Byte running;
	private Date startTime;
	private Date endTime;
	private String runningHost;
	private String cronExpression;


	public SysJob() {
	}

	public SysJob(String id, String jobClass) {
		this.id = id;
		this.jobClass = jobClass;
	}

	public SysJob(String id, String jobClass, Byte running, Date startTime, Date endTime, String runningHost) {
		this.id = id;
		this.jobClass = jobClass;
		this.running = running;
		this.startTime = startTime;
		this.endTime = endTime;
		this.runningHost = runningHost;
	}

	public SysJob(String jobClass, Byte running,Date startTime) {
		this.jobClass = jobClass;
		this.running = running;
		this.startTime =  startTime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "JOB_CLASS", unique = true, nullable = false, length = 40)
	public String getJobClass() {
		return this.jobClass;
	}

	public void setJobClass(String jobClass) {
		this.jobClass = jobClass;
	}

	@Column(name = "RUNNING", precision = 1, scale = 0)
	public Byte getRunning() {
		return this.running;
	}

	public void setRunning(Byte running) {
		this.running = running;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_TIME", length = 7)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_TIME", length = 7)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "RUNNING_HOST", length = 400)
	public String getRunningHost() {
		return this.runningHost;
	}

	public void setRunningHost(String runningHost) {
		this.runningHost = runningHost;
	}
	@Column(name = "CRON_EXPRESSION")
	public String getCronExpression() {
		return cronExpression;
	}

	public void setCronExpression(String cronExpression) {
		this.cronExpression = cronExpression;
	}
}
