package entity.frwk;
// Generated Mar 23, 2023 5:04:07 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * SysMail generated by hbm2java
 */
@Entity
@Table(name = "SYS_MAIL")
public class SysMail implements java.io.Serializable {
	public static final Byte STS_SENDT = 1;
	public static final Byte STS_FALSE = 2;
	private String id;
	private String receipt;
	private String cc;
	private String bcc;
	private String subject;
	private String body;
	private Boolean html;
	private Date sendTime;
	private Byte status;
	private String errorMessage;
	private Date createTime;
	private BigDecimal type;
	private String createBy;
	private List<SysMailAtt> lstAtt = new ArrayList<SysMailAtt>();


	public SysMail() {
		this.createTime = Calendar.getInstance().getTime();
	}

	public SysMail(String id, String receipt, String subject, String body) {
		this.id = id;
		this.receipt = receipt;
		this.subject = subject;
		this.body = body;
	}

	public SysMail(String id, String receipt, String cc, String bcc, String subject, String body, Boolean html,
			Date sendTime, Byte status, String errorMessage, Date createTime, BigDecimal type, String createBy) {
		this.id = id;
		this.receipt = receipt;
		this.cc = cc;
		this.bcc = bcc;
		this.subject = subject;
		this.body = body;
		this.html = html;
		this.sendTime = sendTime;
		this.status = status;
		this.errorMessage = errorMessage;
		this.createTime = createTime;
		this.type = type;
		this.createBy = createBy;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "RECEIPT", nullable = false, length = 1000)
	public String getReceipt() {
		return this.receipt;
	}

	public void setReceipt(String receipt) {
		this.receipt = receipt;
	}

	@Column(name = "CC", length = 1000)
	public String getCc() {
		return this.cc;
	}

	public void setCc(String cc) {
		this.cc = cc;
	}

	@Column(name = "BCC", length = 1000)
	public String getBcc() {
		return this.bcc;
	}

	public void setBcc(String bcc) {
		this.bcc = bcc;
	}

	@Column(name = "SUBJECT", nullable = false, length = 1000)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	
	@Column(name = "BODY", nullable = false, length = 4000)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "HTML", precision = 1, scale = 0)
	public Boolean getHtml() {
		return this.html;
	}

	public void setHtml(Boolean html) {
		this.html = html;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SEND_TIME", length = 7)
	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	@Column(name = "STATUS", precision = 22, scale = 0)
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "ERROR_MESSAGE", length = 2000)
	public String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_TIME", length = 7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "TYPE", precision = 22, scale = 0)
	public BigDecimal getType() {
		return this.type;
	}

	public void setType(BigDecimal type) {
		this.type = type;
	}

	@Column(name = "CREATE_BY", length = 100)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "idSysMail", fetch = FetchType.LAZY)
	public List<SysMailAtt> getLstAtt() {
		return lstAtt;
	}

	public void setLstAtt(List<SysMailAtt> lstAtt) {
		this.lstAtt = lstAtt;
	}
}
