package entity.frwk;
// Generated Mar 23, 2023 5:04:07 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;


/**
 * SysMail generated by hbm2java
 */
@Entity
@Table(name = "SYS_MAIL_ATT")
public class SysMailAtt implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private byte[] fileContent;
	private SysMail idSysMail;
	private String fileName;

	public SysMailAtt() {
	}

	public SysMailAtt(byte[] fileContent, SysMail idSysMail) {
		this.fileContent = fileContent;
		this.idSysMail = idSysMail;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SYS_MAIL")
	public SysMail getIdSysMail() {
		return idSysMail;
	}
	@Column(name = "FILE_CONTENT")
	public byte[] getFileContent() {
		return fileContent;
	}

	public void setFileContent(byte[] fileContent) {
		this.fileContent = fileContent;
	}

	public void setIdSysMail(SysMail idSysMail) {
		this.idSysMail = idSysMail;
	}
	@Column(name = "FILE_NAME", length = 400)
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	
}
