package entity.frwk;
// Generated Mar 24, 2023 5:21:01 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * SysUserMail generated by hbm2java
 */
@Entity
@Table(name = "SYS_USER_MAIL")
public class SysUserMail implements java.io.Serializable {

	private String id;
	private SysDictParam sysDictParam;
	@JsonIgnore
	private SysUsers sysUsers;

	public SysUserMail() {
	}

	public SysUserMail(String id, SysDictParam sysDictParam, SysUsers sysUsers) {
		this.id = id;
		this.sysDictParam = sysDictParam;
		this.sysUsers = sysUsers;
	}

	@Id
	@Column(name = "ID", unique = true, length = 40)
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYS_DICT_PARAM_ID", nullable = false)
	public SysDictParam getSysDictParam() {
		return this.sysDictParam;
	}

	public void setSysDictParam(SysDictParam sysDictParam) {
		this.sysDictParam = sysDictParam;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYS_USER_ID", nullable = false)
	public SysUsers getSysUsers() {
		return this.sysUsers;
	}

	public void setSysUsers(SysUsers sysUsers) {
		this.sysUsers = sysUsers;
	}

}
