package entity;
// Generated Aug 18, 2022 10:38:42 AM by Hibernate Tools 3.6.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import common.util.Formater;
import entity.frwk.SysDictParam;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMERS")
public class Customer implements java.io.Serializable {

	public static final String IS_CUSTOMER = "isCustomer";
	public static final String IS_PARTNER = "isPartner";
	public static final String IS_CUSTOMER_PARTNER = "isCusPart";
	private String id;
	private SysDictParam nationality;
	private Date dateOfEstalishment;
	private String representerId;
	private String representerName;
	private Date representerIdDate;
	private String representerIdIssuePlace;
	private Date representerIdExpireDate;
	private String representerPhone;
	private String representerEmail;
	private String representerAddress;
	private String shortName;
	private String taxCode;
	private String orgAddr;
	private String orgName;
	private String phone;
	private String email;
	private String fax;
	private String code;
	private String description;
	private String businessLicenseNo;
	private String bissType;
	private String strDateOfEstalishment;
	private String strRepresenterIdDate;
	private String strRepresenterIdExpireDate;
	private Boolean isCustomer;
	private Boolean isPartner;
	@Column(name = "IS_CUSTOMER")
	public Boolean getIsCustomer() {
		return isCustomer;
	}

	public void setIsCustomer(Boolean isCustomer) {
		this.isCustomer = isCustomer;
	}

	public Customer() {
	}
	@Column(name = "IS_PARTNER")
	public Boolean getIsPartner() {
		return isPartner;
	}

	public void setIsPartner(Boolean isPartner) {
		this.isPartner = isPartner;
	}
	public Customer(String id, String code, String orgName) {
		this.id = id;
		this.code = code;
		this.orgName = orgName;
	}
	public Customer(String id) {
		this.id = id;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NATIONALITY")
	public SysDictParam getNationality() {
		return nationality;
	}

	public void setNationality(SysDictParam nationality) {
		this.nationality = nationality;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FOUNDED_DATE", length = 7)
	public Date getDateOfEstalishment() {
		return dateOfEstalishment;
	}

	public void setDateOfEstalishment(Date dateOfEstalishment) {
		this.dateOfEstalishment = dateOfEstalishment;
		this.strDateOfEstalishment = Formater.date2str(dateOfEstalishment);
	}

	@Column(name = "REPRESENTER_ID", length = 40)
	public String getRepresenterId() {
		return this.representerId;
	}

	public void setRepresenterId(String representerId) {
		this.representerId = representerId;
	}

	@Column(name = "REPRESENTER_NAME", length = 400)
	public String getRepresenterName() {
		return this.representerName;
	}

	public void setRepresenterName(String representerName) {
		this.representerName = representerName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REPRESENTER_ID_DATE", length = 7)
	public Date getRepresenterIdDate() {
		return this.representerIdDate;
	}

	public void setRepresenterIdDate(Date representerIdDate) {
		this.representerIdDate = representerIdDate;
		this.strRepresenterIdDate = Formater.date2str(representerIdDate);
	}

	@Column(name = "REPRESENTER_ID_ISSUE_PLACE", length = 400)
	public String getRepresenterIdIssuePlace() {
		return this.representerIdIssuePlace;
	}

	public void setRepresenterIdIssuePlace(String representerIdIssuePlace) {
		this.representerIdIssuePlace = representerIdIssuePlace;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REPRESENTER_ID_EXPIRE_DATE", length = 7)
	public Date getRepresenterIdExpireDate() {
		return this.representerIdExpireDate;
	}

	public void setRepresenterIdExpireDate(Date representerIdExpireDate) {
		this.representerIdExpireDate = representerIdExpireDate;
		this.strRepresenterIdExpireDate = Formater.date2str(representerIdExpireDate);
	}

	@Column(name = "REPRESENTER_PHONE", length = 40)
	public String getRepresenterPhone() {
		return this.representerPhone;
	}

	public void setRepresenterPhone(String representerPhone) {
		this.representerPhone = representerPhone;
	}

	@Column(name = "REPRESENTER_EMAIL", length = 40)
	public String getRepresenterEmail() {
		return this.representerEmail;
	}

	public void setRepresenterEmail(String representerEmail) {
		this.representerEmail = representerEmail;
	}

	@Column(name = "REPRESENTER_ADDRESS", length = 4000)
	public String getRepresenterAddress() {
		return this.representerAddress;
	}

	public void setRepresenterAddress(String representerAddress) {
		this.representerAddress = representerAddress;
	}

	@Column(name = "SHORT_NAME", length = 400)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "TAX_CODE", length = 20)
	public String getTaxCode() {
		return this.taxCode;
	}

	public void setTaxCode(String taxCode) {
		this.taxCode = taxCode;
	}

	@Column(name = "ORG_ADDR", length = 1000)
	public String getOrgAddr() {
		return this.orgAddr;
	}

	public void setOrgAddr(String orgAddr) {
		this.orgAddr = orgAddr;
	}

	@Column(name = "ORG_NAME", length = 1000)
	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	@Column(name = "PHONE", length = 24)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "EMAIL", length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "FAX", length = 200)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "CODE", length = 200)
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "DESCRIPTION", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "BUSINESS_LICENSE_NO", nullable = false, length = 200)
	public String getBusinessLicenseNo() {
		return this.businessLicenseNo;
	}

	public void setBusinessLicenseNo(String businessLicenseNo) {
		this.businessLicenseNo = businessLicenseNo;
	}

	@Column(name = "BISS_TYPE", length = 4000)
	public String getBissType() {
		return this.bissType;
	}

	public void setBissType(String bissType) {
		this.bissType = bissType;
	}

	@Transient
	public String getStrDateOfEstalishment() {
		return strDateOfEstalishment;
	}

	public void setStrDateOfEstalishment(String strDateOfEstalishment) throws Exception {
		this.strDateOfEstalishment = strDateOfEstalishment;
		this.dateOfEstalishment = Formater.str2date(strDateOfEstalishment);
	}

	@Transient
	public String getStrRepresenterIdDate() {
		return strRepresenterIdDate;
	}

	public void setStrRepresenterIdDate(String strRepresenterIdDate) throws Exception {
		this.strRepresenterIdDate = strRepresenterIdDate;
		this.representerIdDate = Formater.str2date(strRepresenterIdDate);
	}

	@Transient
	public String getStrRepresenterIdExpireDate() {
		return strRepresenterIdExpireDate;
	}

	public void setStrRepresenterIdExpireDate(String strRepresenterIdExpireDate) throws Exception {
		this.strRepresenterIdExpireDate = strRepresenterIdExpireDate;
		this.representerIdExpireDate = Formater.str2date(strRepresenterIdExpireDate);
	}

	@Transient
	private String newOrderCode;

	@Transient
	public String getNewOrderCode() {
		return newOrderCode;
	}

	public void setNewOrderCode(String newOrderCode) {
		this.newOrderCode = newOrderCode;
	}

}
