package entity;
// Generated Apr 25, 2023 9:27:50 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * QcInDetail generated by hbm2java
 */
@Entity
@Table(name = "QC_IN_DETAIL")
public class QcInDetail implements java.io.Serializable {

	private String id;
	private QcIn qcIn;
	private QcOsDetail qcOsDetail;
	private Long ngAmount;
	private Long brokenAmount;
	private Long amount;

	public QcInDetail() {
	}

	public QcInDetail(String id, QcIn qcIn, QcOsDetail qcOsDetail) {
		this.id = id;
		this.qcIn = qcIn;
		this.qcOsDetail = qcOsDetail;
	}

	public QcInDetail(String id, QcIn qcIn, QcOsDetail qcOsDetail, Long ngAmount, Long brokenAmount, Long amount) {
		this.id = id;
		this.qcIn = qcIn;
		this.qcOsDetail = qcOsDetail;
		this.ngAmount = ngAmount;
		this.brokenAmount = brokenAmount;
		this.amount = amount;
	}

	public QcInDetail(QcIn qcIn) {
		this.qcIn = qcIn;
		this.amount= qcIn.getAmount();
		this.brokenAmount= qcIn.getBrokenAmount();
		this.ngAmount= qcIn.getNgAmount();
		this.qcOsDetail = qcIn.getQcOs().getQcOsDetails().get(0);
		
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 40)
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QC_IN_ID", nullable = false)
	public QcIn getQcIn() {
		return this.qcIn;
	}

	public void setQcIn(QcIn qcIn) {
		this.qcIn = qcIn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QC_OS_DETAIL_ID", nullable = false)
	public QcOsDetail getQcOsDetail() {
		return this.qcOsDetail;
	}

	public void setQcOsDetail(QcOsDetail qcOsDetail) {
		this.qcOsDetail = qcOsDetail;
	}

	@Column(name = "NG_AMOUNT", precision = 15, scale = 0)
	public Long getNgAmount() {
		return this.ngAmount;
	}

	public void setNgAmount(Long ngAmount) {
		this.ngAmount = ngAmount;
	}

	@Column(name = "BROKEN_AMOUNT", precision = 15, scale = 0)
	public Long getBrokenAmount() {
		return this.brokenAmount;
	}

	public void setBrokenAmount(Long brokenAmount) {
		this.brokenAmount = brokenAmount;
	}

	@Column(name = "AMOUNT", precision = 15, scale = 0)
	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

}
